---
title: "Mini Project 2"
author: "Mathena Abramson"
date: "October 23, 2017"
output: html_document
---

```{r, message = FALSE}
library(tidyverse)
load("house_elections.rda")
load("candidates.rda")
load("committees.rda")
load("contributions.rda")
library(ggthemes)
```

```{r}
glimpse(house_elections)
glimpse(candidates)
glimpse(committees)
glimpse(contributions)
```

```{r}
cand12 <- candidates %>%
  filter(cand_office == "H")
  
cand_contrib <- cand12 %>%
  inner_join(contributions, by = "cand_id") %>%
  select(1:8, -7, 16, 19, 21:23, 27:30, 35)
  
glimpse(cand_contrib)
```

```{r}
new_comm <- select(committees, -15)

comm_cand_contrib <- cand_contrib %>%
  inner_join(new_comm, by = "cmte_id") %>%
  select(1:12, 15:19, 25:30)
arrange(comm_cand_contrib, cand_name)
```

```{r}
house_elections <- house_elections %>%
  rename(cand_id = fec_id)

full_contrib <- comm_cand_contrib %>%
  inner_join(house_elections, by = "cand_id")

glimpse(full_contrib)
```

```{r}
state_funct <- function(state_arg) {
  full_contrib %>%
    filter(state == state_arg) %>%
    group_by(cand_name) %>%
    summarize(total_transaction = sum(transaction_amt), 
              victory = any(ge_winner == "W"),
              district = first(district)) %>%
    ggplot(aes(x = cand_name, y = total_transaction)) +
    geom_bar(stat = "identity", aes(fill = victory)) +
    scale_fill_manual(values = c("#004f71", "#465a01")) +
    theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  labs(x = "U.S. House of Representatives Candidates") +
  labs(y = "Sum of Contributions Recieved ") +
  labs(title = "Total Contributions Recieved by House of Representatives Candidates")
    
}


NE_cand <- c("ME", "NH", "VT", "MA", "RI", "CT")    
lapply(NE_cand, FUN = state_funct)
```
